### ISSUE TITLE
Test pre handler

### ISSUE THREAD

**Issue by terryx** [pashariger/testing-hapi#18]
How do you test pre handler ? Do you stub a request and response object ?

**Comment by pashariger** [comment]
Apologies for not seeing this sooner.

By pre-handler, I assume you mean hapi route validation. Yes, I would stub a request (and credentials object if you are using authentication) and then user Server.inject and test the response object. If you test with invalid data you could expect the response.statusCode to be 400, and if you pass valid data, you could check for a 200 statusCode, as well as test against a stubbed response.

Hope this is helpful. Adding a todo to add an example for this.
